//! Command-name routing for the built-in socket CLI surface.

pub(super) fn is_socket_cli_global_option(option: &str) -> bool {
    matches!(option, "--json" | "--verbose" | "--debug" | "--socket")
        || option.starts_with("--socket=")
}

pub(super) fn is_socket_cli_command(command: &str) -> bool {
    #[cfg(feature = "browser")]
    if command == "browser" {
        return true;
    }

    matches!(
        command,
        "list"
            | "create-workspace"
            | "focus"
            | "close-workspace"
            | "notify"
            | "surfaces"
            | "surface-list"
            | "surface:list"
            | "split-surface"
            | "surface-split"
            | "surface:split"
            | "focus-surface"
            | "surface-focus"
            | "surface:focus"
            | "close-surface"
            | "surface-close"
            | "surface:close"
            | "new-tab"
            | "pane-new-tab"
            | "pane:new-tab"
            | "select-tab"
            | "pane-select-tab"
            | "pane:select-tab"
            | "send-text"
            | "send_text"
            | "read-screen"
            | "read_screen"
            | "surface-read-text"
            | "surface:read-text"
            | "capture-tail"
            | "capture_tail"
            | "surface-capture-tail"
            | "surface:capture-tail"
            | "worktree-list"
            | "worktree:list"
            | "worktree.list"
            | "worktree-status"
            | "worktree:status"
            | "worktree.status"
            | "worktree-create"
            | "worktree:create"
            | "worktree.create"
            | "worktree-attach"
            | "worktree:attach"
            | "worktree.attach"
            | "worktree-remove"
            | "worktree:remove"
            | "worktree.remove"
            | "worktree-merge"
            | "worktree:merge"
            | "worktree.merge"
            | "worktree-doctor"
            | "worktree:doctor"
            | "worktree.doctor"
            | "actions"
            | "project-actions"
            | "project:action:list"
            | "project.action.list"
            | "action-run"
            | "project-action-run"
            | "project:action:run"
            | "project.action.run"
            | "set-status"
            | "list-status"
            | "clear-status"
            | "set-progress"
            | "list-progress"
            | "clear-progress"
            | "log"
            | "logs"
            | "list-logs"
            | "clear-logs"
            | "notifications"
            | "clear-notifications"
            | "notifications-clear"
            | "notification:clear"
            | "hooks"
            | "ping"
            | "identify"
            | "system-identify"
            | "system:identify"
            | "system.identify"
            | "capabilities"
            | "wait"
            | "events"
            | "examples"
            | "completion"
            | "completions"
            | "agents"
            | "agent-list"
            | "agent:list"
            | "agent-health"
            | "agent:health"
            | "agent-reclaim-plan"
            | "agent:reclaim-plan"
            | "agent.reclaim.plan"
            | "hibernate-agent"
            | "agent-hibernate"
            | "agent:hibernate"
            | "agent.hibernate"
            | "reclaim-agents"
            | "agent-reclaim"
            | "agent:reclaim"
            | "agent.reclaim"
            | "resume-agent"
            | "agent-resume"
            | "agent:resume"
            | "status"
            | "statusline"
            | "status-line"
            | "status:summary"
            | "context-snapshot"
            | "context_snapshot"
            | "context:snapshot"
            | "context.snapshot"
            | "top"
            | "tree"
            | "topology-tree"
            | "topology:tree"
            | "topology.tree"
            | "remotes"
            | "remote-list"
            | "remote:list"
            | "remote.list"
            | "remote-status"
            | "remote:status"
            | "remote.status"
            | "ssh"
    )
}
