[package]
name = "forktty-ui-gtk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
description = "ForkTTY GTK4/libadwaita application shell"

[[bin]]
name = "forktty"
path = "src/main.rs"

[features]
default = []
gtk-vte = ["dep:adw", "dep:gtk4", "dep:global-hotkey", "dep:libloading", "forktty-terminal/vte"]

[dependencies]
forktty-core = { path = "../forktty-core" }
forktty-socket = { path = "../forktty-socket" }
forktty-terminal = { path = "../forktty-terminal" }
adw = { package = "libadwaita", version = "0.8", features = ["v1_4"], optional = true }
global-hotkey = { version = "0.8", optional = true }
gtk4 = { version = "0.10", optional = true }
libloading = { version = "0.9", optional = true }
tokio.workspace = true
